"""summaries.model

Revision ID: 1a207020bf1e
Revises: 6b0aefef6bd7
Create Date: 2024-09-11 17:31:26.195691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a207020bf1e'
down_revision: Union[str, None] = '6b0aefef6bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('model', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'model')
    # ### end Alembic commands ###
