"""summaries.warnings

Revision ID: 5539078dc40e
Revises: 1a207020bf1e
Create Date: 2024-09-11 20:48:17.931618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5539078dc40e'
down_revision: Union[str, None] = '1a207020bf1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('warnings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'warnings')
    # ### end Alembic commands ###
