"""Added Ingredient Alias

Revision ID: 71e4a38f548e
Revises: 75c820133172
Create Date: 2024-09-09 22:18:55.741011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e4a38f548e'
down_revision: Union[str, None] = '75c820133172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('alias', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'ingredients', ['alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.drop_column('ingredients', 'alias')
    # ### end Alembic commands ###
